all:
	gcc -g3 -lm -o test_led_info_get_result TEST_onlp_ledi_info_get.c -L/lib/x86_64-linux-gnu/ -lonlp-platform -lonlp

	gcc -g3 -lm -o test_led_mode_set_result TEST_onlp_ledi_mode_set.c -L/lib/x86_64-linux-gnu/ -lonlp-platform -lonlp


# -L/lib/x86_64-linux-gnu/ -lonlp-platform -lonlp => 代表要到-L/lib/x86_64-linux-gnu/ 路徑下查找文件