all:
	gcc -g3 -lm -o 1_onlp_sysi_platform_get_RESULT 1_onlp_sysi_platform_get.c -L/lib/x86_64-linux-gnu/ -lonlp-platform -lonlp

	gcc -g3 -lm -o 2_onlp_sysi_init_RESULT 2_onlp_sysi_init.c -L/lib/x86_64-linux-gnu/ -lonlp-platform -lonlp

	gcc -g3 -lm -o 3_onlp_sysi_onie_data_get_RESULT 3_onlp_sysi_onie_data_get.c -L/lib/x86_64-linux-gnu/ -lonlp-platform -lonlp

	gcc -g3 -lm -o 4_onlp_sysi_onie_data_free_RESULT 4_onlp_sysi_onie_data_free.c -L/lib/x86_64-linux-gnu/ -lonlp-platform -lonlp

	gcc -g3 -lm -o 5_onlp_sysi_oids_get_RESULT 5_onlp_sysi_oids_get.c -L/lib/x86_64-linux-gnu/ -lonlp-platform -lonlp

	gcc -g3 -lm -o 6_onlp_sysi_platform_info_get_RESULT 6_onlp_sysi_platform_info_get.c -L/lib/x86_64-linux-gnu/ -lonlp-platform -lonlp

	gcc -g3 -lm -o 7_onlp_sysi_platform_info_free_RESULT 7_onlp_sysi_platform_info_free.c -L/lib/x86_64-linux-gnu/ -lonlp-platform -lonlp