all:
	gcc -g3 -lm -o 1_onlp_sfpi_init_RESULT 1_onlp_sfpi_init.c -L/lib/x86_64-linux-gnu/ -lonlp-platform -lonlp

	gcc -g3 -lm -o 2_onlp_sfpi_bitmap_get_RESULT 2_onlp_sfpi_bitmap_get.c -L/lib/x86_64-linux-gnu/ -lonlp-platform -lonlp

	gcc -g3 -lm -o 3_onlp_sfpi_is_present_RESULT 3_onlp_sfpi_is_present.c -L/lib/x86_64-linux-gnu/ -lonlp-platform -lonlp

	gcc -g3 -lm -o 4_onlp_sfpi_presence_bitmap_get_RESULT 4_onlp_sfpi_presence_bitmap_get.c -L/lib/x86_64-linux-gnu/ -lonlp-platform -lonlp

	gcc -g3 -lm -o 5_onlp_sfpi_rx_los_bitmap_get_RESULT 5_onlp_sfpi_rx_los_bitmap_get.c -L/lib/x86_64-linux-gnu/ -lonlp-platform -lonlp

	gcc -g3 -lm -o 6_onlp_sfpi_eeprom_read_RESULT 6_onlp_sfpi_eeprom_read.c -L/lib/x86_64-linux-gnu/ -lonlp-platform -lonlp

	gcc -g3 -lm -o 7_onlp_sfpi_dev_readb_RESULT 7_onlp_sfpi_dev_readb.c -L/lib/x86_64-linux-gnu/ -lonlp-platform -lonlp

	gcc -g3 -lm -o 8_onlp_sfpi_dev_writeb_RESULT 8_onlp_sfpi_dev_writeb.c -L/lib/x86_64-linux-gnu/ -lonlp-platform -lonlp

	gcc -g3 -lm -o 9_onlp_sfpi_dev_readw_RESULT 9_onlp_sfpi_dev_readw.c -L/lib/x86_64-linux-gnu/ -lonlp-platform -lonlp

	gcc -g3 -lm -o 10_onlp_sfpi_dev_writew_RESULT 10_onlp_sfpi_dev_writew.c -L/lib/x86_64-linux-gnu/ -lonlp-platform -lonlp

	gcc -g3 -lm -o 11_onlp_sfpi_dev_read_RESULT 11_onlp_sfpi_dev_read.c -L/lib/x86_64-linux-gnu/ -lonlp-platform -lonlp

	gcc -g3 -lm -o 12_onlp_sfpi_dev_write_RESULT 12_onlp_sfpi_dev_write.c -L/lib/x86_64-linux-gnu/ -lonlp-platform -lonlp

	gcc -g3 -lm -o 13_onlp_sfpi_dom_read_RESULT 13_onlp_sfpi_dom_read.c -L/lib/x86_64-linux-gnu/ -lonlp-platform -lonlp

	gcc -g3 -lm -o 14_onlp_sfpi_control_supported_RESULT 14_onlp_sfpi_control_supported.c -L/lib/x86_64-linux-gnu/ -lonlp-platform -lonlp

	gcc -g3 -lm -o 15_onlp_sfpi_control_set_RESULT 15_onlp_sfpi_control_set.c -L/lib/x86_64-linux-gnu/ -lonlp-platform -lonlp

	gcc -g3 -lm -o 16_onlp_sfpi_control_get_RESULT 16_onlp_sfpi_control_get.c -L/lib/x86_64-linux-gnu/ -lonlp-platform -lonlp

	gcc -g3 -lm -o 17_onlp_sfpi_denit_RESULT 17_onlp_sfpi_denit.c -L/lib/x86_64-linux-gnu/ -lonlp-platform -lonlp


