all:
	gcc -g3 -lm -o 1_onlp_thermali_init_RESULT 1_onlp_thermali_init.c -L/lib/x86_64-linux-gnu/ -lonlp-platform -lonlp

	gcc -g3 -lm -o 2_onlp_thermali_info_get_RESULT 2_onlp_thermali_info_get.c -L/lib/x86_64-linux-gnu/ -lonlp-platform -lonlp

	gcc -g3 -lm -o 3_onlp_thermali_status_get_RESULT 3_onlp_thermali_status_get.c -L/lib/x86_64-linux-gnu/ -lonlp-platform -lonlp

	gcc -g3 -lm -o 4_onlp_thermali_hdr_get_RESULT 4_onlp_thermali_hdr_get.c -L/lib/x86_64-linux-gnu/ -lonlp-platform -lonlp
