all:
	gcc -g3 -lm -o 1_onlp_psui_init_RESULT 1_onlp_psui_init.c -L/lib/x86_64-linux-gnu/ -lonlp-platform -lonlp
	gcc -g3 -lm -o 2_onlp_psui_info_get_RESULT 2_onlp_psui_info_get.c -L/lib/x86_64-linux-gnu/ -lonlp-platform -lonlp
	gcc -g3 -lm -o 3_onlp_psui_status_get_RESULT 3_onlp_psui_status_get.c -L/lib/x86_64-linux-gnu/ -lonlp-platform -lonlp
	gcc -g3 -lm -o 4_onlp_psui_hdr_get_RESULT 4_onlp_psui_hdr_get.c -L/lib/x86_64-linux-gnu/ -lonlp-platform -lonlp
